<a href="https://colab.research.google.com/github/FaYMan2/Models-from-scratch/blob/main/ANN_FROM_SCRATCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## In this notebook we will be creating a ANN using only numpy and python, this will help us understand how ANN work behind the scene

#### ANN (articifial neural network) consisits of neorons which are like nodes which are connect to nodes ( neurons ) of the next layer are previous layers by some values called weights and biases, each neuron can be thought of as its own Linear regression and combination of multiple neurons who are trying to find the best fit come together to create non-linearity


###Firstly we need to devise a method to initialise structure of ANN
###ANN consits of neurons which are connected to ever neuron behind it ie Neuron $N_{i,j}$ is connected to $N_{i-1,k} ∀k ∈ (0,j)$ by some Weight and bias values, this structure is called a dense layer.

### First idea that comes to mind is to create a array/list to store number of neuron each layer. This way we also know the number of layers in the Network by the list length so.

### Secondly we can create a 3-d matrix Any * Any * 2 - layers where $layers[i][j][0]$ will store all the weights corresponding to the $i^{th}$ layer's $j^{th}$ neuron and $layers[i][j][1]$ will store the biases for the same.

### To initialise the values of the neurons we will use the numpy random package and initalise random values to each weight initally, WHY!? you can read about it through the links in the end of the notebook.



In [7]:
## Code snippet for the above


#Example
structure : list[int] = [4,3,4,2]

def __init__layers(structure):
    layers = []
    for i in range(1,len(structure)):
      weights = np.random.rand(structure[i],structure[i-1])
      bias = np.ones(structure[i-1])
      layers.append([weights,bias])
    return layers


layers = __init__layers(structure)

print(layers[0][0])


[[0.35513763 0.69506169 0.15917674 0.47745829]
 [0.47037855 0.66170052 0.82847528 0.52084076]
 [0.49845742 0.74958829 0.55583285 0.33680429]]


### Now lets create a method to feedforward(get outputs) from out network
### A neuron get its ouput by - $ y^{'} = ∑_{i=0}^{n}(Wᵢ.Xᵢ + b_i) $
### also we will need a actiavtion function here we will use RELU  

In [ ]:


def feedforward(x):
  output = [x.copy()]
  for i in range(len(x)):


[[0.83656022 0.37431486]
 [0.20860903 0.51797112]
 [0.69305219 0.5888257 ]
 [0.18981239 0.28017572]
 [0.47367012 0.39235807]]
